version: '3.8'

services:
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: empleadosdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: dark
      MYSQL_PASSWORD: Dark230900.
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angularjs-frontend
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - laravel

volumes:
  mysql_data: